name: API Check
on: [ pull_request ]

jobs:
  api-check:
    name: Binary Compatibility Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Set JDK version
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2
      - name: Run API Check
        run: bash ./gradlew apiCheck
