name: API Check
on: [ pull_request ]

jobs:
  api-check:
    name: Binary Compatibility Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
      - name: Set JDK version
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # v2
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2
      - name: Run API Check
        run: bash ./gradlew apiCheck
