name: Publish SNAPSHOT

on:
  push:
    branches:
      - main

jobs:
  publish-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Set JDK version
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2
      - name: Publish artifact
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey : ${{ secrets.NEXUS_PUBLISH_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId : ${{ secrets.NEXUS_PUBLISH_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword : ${{ secrets.NEXUS_PUBLISH_SIGNING_KEY_PASSWORD }}

          # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
          # If we split on '/' and take the 3rd value,
          # we can get the release name.
        run: |
          echo "New version: $(grep "VERSION_NAME" gradle.properties | cut -d'=' -f2)"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew clean -x test -x lint publish :whetstone-gradle-plugin:publish
