name: Run tests
on:
  pull_request:
  push:
    branches:
      - renovate/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Set JDK version
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3
        with:
          distribution: zulu
          java-version: 17
      - name: Run unit tests
        run: ./gradlew -x sample:testDebugUnitTest whetstone-compiler:test testDebugUnitTest
      - name: Build sample app
        run: ./gradlew sample:assembleDebug
